---
title: "Final Project"
author: "Zane Brotherton, Nate Adam, Feolu Kolawole"
date: "2023-08-14"
output: pdf_document
---

*The study*: In this section, you should give a description of the study underlying the dataset. Possible
questions to be answered are the following:
  This data
  
*The data*: In this section, you should describe the data set and possibly do some exploratory data
analysis. For instance:

*The models*: In this section, you should develop a model for the data that will allow them to answer
some of the specific goals of the study. Possible questions to be addressed here are the following:

*Results*: In this section, you should report the results obtained by fitting the proposed models in the
previous section. Emphasis should be placed on clarity, as if the report were a statistical consultant’s
report for a nonstatistician. For instance, loads of R output would, in general, not be acceptable. Plots
and well-organized tables are good things to have in this section. Possible questions to be addressed
here are the following:

*Appendix*: In this section, you should attach a final, editied, copy of the R code used in the analysis.
Ideally, there will be comments in the file, i.e. lines beginning with “#” to clarify what each part of the code is doing.

*Acknowledgements*: If you consult outside sources that refer to this data set, you should cite these
as references, and describe what you used from each source. Sources include material found on the
internet, journal articles and books.

```{r read_data, eval=T, echo=T}
url_path = "https://raw.githubusercontent.com/dlsun/pods/master/data/covid/"
```
